"""
Hypernet Life Story Timeline Engine

Builds a unified chronological timeline from all data sources in a
personal account. The timeline is the backbone of the Life Story —
every email, photo, social post, document, and event placed on a
single navigable axis.

Features:
  - Unified timeline from heterogeneous sources
  - Event clustering: groups related items into chapters
  - Zoom levels: day, week, month, year, decade, life
  - Entity extraction: people, places, organizations mentioned
  - Cross-linking: automatically creates Hypernet links between related items

Architecture: docs/architecture/personal-accounts-and-life-story.md §Life Story

Usage:
    timeline = TimelineEngine(store, account_address="1.local.1")
    timeline.rebuild()                    # Full rebuild from all nodes
    timeline.add_event(node)              # Add a single event

    # Query
    events = timeline.query(
        start=datetime(2024, 1, 1),
        end=datetime(2024, 12, 31),
        zoom="month",
    )

    # Get chapters (auto-detected clusters)
    chapters = timeline.get_chapters()
"""

from __future__ import annotations

import json
import logging
import re
from collections import defaultdict
from dataclasses import dataclass, field
from datetime import datetime, timezone, timedelta
from enum import Enum
from pathlib import Path
from typing import Optional

from ..address import HypernetAddress
from ..node import Node
from ..store import Store

log = logging.getLogger(__name__)


class ZoomLevel(Enum):
    """Timeline zoom levels."""
    DAY = "day"
    WEEK = "week"
    MONTH = "month"
    YEAR = "year"
    DECADE = "decade"
    LIFE = "life"


@dataclass
class TimelineEvent:
    """A single event on the timeline.

    Every node with a timestamp becomes a TimelineEvent. Events are
    the atomic unit of the Life Story.
    """
    address: str                    # Hypernet address of the source node
    timestamp: datetime             # When it happened
    title: str = ""                 # Short description
    source_type: str = ""           # email, photo, social_post, document, etc.
    source_platform: str = ""       # gmail, instagram, local, etc.
    people: list[str] = field(default_factory=list)     # People mentioned/involved
    places: list[str] = field(default_factory=list)     # Locations
    tags: list[str] = field(default_factory=list)       # User or auto-generated tags
    chapter_id: Optional[str] = None  # Which chapter this belongs to

    def to_dict(self) -> dict:
        return {
            "address": self.address,
            "timestamp": self.timestamp.isoformat(),
            "title": self.title,
            "source_type": self.source_type,
            "source_platform": self.source_platform,
            "people": self.people,
            "places": self.places,
            "tags": self.tags,
            "chapter_id": self.chapter_id,
        }

    @classmethod
    def from_dict(cls, d: dict) -> TimelineEvent:
        return cls(
            address=d["address"],
            timestamp=datetime.fromisoformat(d["timestamp"]),
            title=d.get("title", ""),
            source_type=d.get("source_type", ""),
            source_platform=d.get("source_platform", ""),
            people=d.get("people", []),
            places=d.get("places", []),
            tags=d.get("tags", []),
            chapter_id=d.get("chapter_id"),
        )


@dataclass
class Chapter:
    """A detected cluster of related events.

    Chapters are auto-generated by analyzing temporal proximity
    and shared entities (people, places, tags). Users can also
    create chapters manually.

    Examples: "Trip to Denver", "Job Interview Period", "Holiday 2024"
    """
    chapter_id: str
    title: str
    start: datetime
    end: datetime
    event_count: int = 0
    dominant_type: str = ""         # Most common source_type in the chapter
    key_people: list[str] = field(default_factory=list)
    key_places: list[str] = field(default_factory=list)
    auto_generated: bool = True     # False if user-created

    def duration_days(self) -> float:
        return (self.end - self.start).total_seconds() / 86400

    def to_dict(self) -> dict:
        return {
            "chapter_id": self.chapter_id,
            "title": self.title,
            "start": self.start.isoformat(),
            "end": self.end.isoformat(),
            "event_count": self.event_count,
            "duration_days": round(self.duration_days(), 1),
            "dominant_type": self.dominant_type,
            "key_people": self.key_people,
            "key_places": self.key_places,
            "auto_generated": self.auto_generated,
        }


class TimelineEngine:
    """Builds and queries a unified timeline for a personal account."""

    def __init__(self, store: Store, account_address: str,
                 data_dir: str | Path = "data"):
        self.store = store
        self.account_address = account_address
        self.data_dir = Path(data_dir)
        self._events: list[TimelineEvent] = []
        self._chapters: list[Chapter] = []
        self._index_path = self.data_dir / "timelines" / f"{account_address.replace('.', '_')}.json"
        self._load_index()

    # ── Index Persistence ───────────────────────────────────────────

    def _load_index(self) -> None:
        """Load timeline index from disk."""
        if self._index_path.exists():
            try:
                data = json.loads(self._index_path.read_text(encoding="utf-8"))
                self._events = [TimelineEvent.from_dict(e) for e in data.get("events", [])]
                self._chapters = [Chapter(
                    chapter_id=c["chapter_id"],
                    title=c["title"],
                    start=datetime.fromisoformat(c["start"]),
                    end=datetime.fromisoformat(c["end"]),
                    event_count=c.get("event_count", 0),
                    dominant_type=c.get("dominant_type", ""),
                    key_people=c.get("key_people", []),
                    key_places=c.get("key_places", []),
                    auto_generated=c.get("auto_generated", True),
                ) for c in data.get("chapters", [])]
            except (json.JSONDecodeError, OSError, KeyError) as e:
                log.warning("Failed to load timeline index: %s", e)

    def _save_index(self) -> None:
        """Persist timeline index to disk."""
        self._index_path.parent.mkdir(parents=True, exist_ok=True)
        data = {
            "account": self.account_address,
            "event_count": len(self._events),
            "chapter_count": len(self._chapters),
            "updated": datetime.now(timezone.utc).isoformat(),
            "events": [e.to_dict() for e in self._events],
            "chapters": [c.to_dict() for c in self._chapters],
        }
        self._index_path.write_text(
            json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8"
        )

    # ── Event Extraction ────────────────────────────────────────────

    def _extract_timestamp(self, node: Node) -> Optional[datetime]:
        """Extract the best timestamp from a node's data.

        Checks multiple fields in priority order, since different
        source types store timestamps differently.
        """
        data = node.data
        for field_name in [
            "timestamp", "date", "sent_at", "taken_at", "created_at",
            "published_at", "received_at", "event_date", "created",
        ]:
            val = data.get(field_name)
            if val:
                try:
                    if isinstance(val, str):
                        return datetime.fromisoformat(val.replace("Z", "+00:00"))
                    elif isinstance(val, (int, float)):
                        return datetime.fromtimestamp(val, tz=timezone.utc)
                except (ValueError, OSError):
                    continue

        # Fall back to node's own created_at
        if node.created_at:
            if isinstance(node.created_at, datetime):
                return node.created_at
            try:
                return datetime.fromisoformat(
                    str(node.created_at).replace("Z", "+00:00")
                )
            except (ValueError, AttributeError):
                pass

        return None

    def _extract_title(self, node: Node) -> str:
        """Extract a human-readable title from a node."""
        data = node.data
        for field_name in ["title", "subject", "name", "display_name", "filename", "label"]:
            val = data.get(field_name)
            if val and isinstance(val, str):
                return val[:200]
        return str(node.address)

    def _extract_people(self, node: Node) -> list[str]:
        """Extract people mentioned in a node."""
        people = []
        data = node.data

        # Explicit people fields
        for field_name in ["from", "sender", "to", "recipients", "participants",
                          "tagged_people", "people", "author"]:
            val = data.get(field_name)
            if isinstance(val, str) and val:
                people.append(val)
            elif isinstance(val, list):
                people.extend(str(v) for v in val if v)

        return list(set(people))

    def _extract_places(self, node: Node) -> list[str]:
        """Extract locations from a node."""
        places = []
        data = node.data

        for field_name in ["location", "place", "city", "venue", "address"]:
            val = data.get(field_name)
            if isinstance(val, str) and val:
                places.append(val)
            elif isinstance(val, dict):
                # GPS or structured location
                name = val.get("name") or val.get("city") or val.get("formatted")
                if name:
                    places.append(name)

        return list(set(places))

    def _extract_source_info(self, node: Node) -> tuple[str, str]:
        """Extract source type and platform from a node."""
        data = node.data
        source_type = data.get("source_type", data.get("type", ""))
        source_platform = data.get("source_platform", data.get("platform", ""))

        # Infer from address if not explicit
        if not source_type:
            addr = str(node.address)
            if ".3.0" in addr or ".3.0." in addr:
                source_type = "email"
            elif ".8." in addr or ".6.1" in addr:
                source_type = "media"
            elif ".6.2" in addr:
                source_type = "social"
            elif ".5." in addr:
                source_type = "task"
            elif ".9." in addr:
                source_type = "note"

        return source_type, source_platform

    def node_to_event(self, node: Node) -> Optional[TimelineEvent]:
        """Convert a Hypernet node to a TimelineEvent.

        Returns None if the node has no usable timestamp.
        """
        timestamp = self._extract_timestamp(node)
        if not timestamp:
            return None

        source_type, source_platform = self._extract_source_info(node)

        return TimelineEvent(
            address=str(node.address),
            timestamp=timestamp,
            title=self._extract_title(node),
            source_type=source_type,
            source_platform=source_platform,
            people=self._extract_people(node),
            places=self._extract_places(node),
            tags=node.data.get("tags", node.data.get("flags", [])),
        )

    # ── Building the Timeline ───────────────────────────────────────

    def add_event(self, node: Node) -> Optional[TimelineEvent]:
        """Add a single node to the timeline.

        Returns the event if added, None if the node has no timestamp.
        """
        # Skip if already in timeline
        addr = str(node.address)
        if any(e.address == addr for e in self._events):
            return None

        event = self.node_to_event(node)
        if event:
            self._events.append(event)
            self._events.sort(key=lambda e: e.timestamp)
            return event
        return None

    def rebuild(self) -> int:
        """Rebuild the entire timeline from all nodes in the account.

        Returns the number of events found.
        """
        prefix = HypernetAddress.parse(self.account_address)
        all_nodes = self.store.list_nodes(prefix=prefix)

        self._events = []
        for node in all_nodes:
            event = self.node_to_event(node)
            if event:
                self._events.append(event)

        # Sort chronologically
        self._events.sort(key=lambda e: e.timestamp)

        # Detect chapters
        self._chapters = self._detect_chapters()

        # Assign events to chapters
        for event in self._events:
            for chapter in self._chapters:
                if chapter.start <= event.timestamp <= chapter.end:
                    event.chapter_id = chapter.chapter_id
                    break

        self._save_index()
        log.info(
            "Timeline rebuilt: %d events, %d chapters for %s",
            len(self._events), len(self._chapters), self.account_address,
        )
        return len(self._events)

    # ── Chapter Detection ───────────────────────────────────────────

    def _detect_chapters(self, gap_days: float = 3.0,
                         min_events: int = 3) -> list[Chapter]:
        """Detect event clusters (chapters) using temporal proximity.

        Algorithm:
        1. Walk events chronologically
        2. If gap between consecutive events > gap_days, start new cluster
        3. Clusters with >= min_events become chapters
        4. Analyze each chapter for dominant type, key people/places
        5. Generate a descriptive title

        Args:
            gap_days: Maximum gap (in days) between events in the same cluster
            min_events: Minimum events to form a chapter
        """
        if not self._events:
            return []

        clusters: list[list[TimelineEvent]] = []
        current_cluster: list[TimelineEvent] = [self._events[0]]

        for event in self._events[1:]:
            prev = current_cluster[-1]
            gap = (event.timestamp - prev.timestamp).total_seconds() / 86400

            if gap > gap_days:
                clusters.append(current_cluster)
                current_cluster = [event]
            else:
                current_cluster.append(event)

        clusters.append(current_cluster)

        # Convert qualifying clusters to chapters
        chapters = []
        for i, cluster in enumerate(clusters):
            if len(cluster) < min_events:
                continue

            # Analyze cluster
            type_counts: dict[str, int] = defaultdict(int)
            all_people: list[str] = []
            all_places: list[str] = []

            for event in cluster:
                if event.source_type:
                    type_counts[event.source_type] += 1
                all_people.extend(event.people)
                all_places.extend(event.places)

            dominant_type = max(type_counts, key=type_counts.get) if type_counts else ""

            # Count people/places by frequency
            people_counts = defaultdict(int)
            for p in all_people:
                people_counts[p] += 1
            place_counts = defaultdict(int)
            for p in all_places:
                place_counts[p] += 1

            key_people = sorted(people_counts, key=people_counts.get, reverse=True)[:5]
            key_places = sorted(place_counts, key=place_counts.get, reverse=True)[:3]

            # Generate title
            title = self._generate_chapter_title(
                cluster, dominant_type, key_people, key_places,
            )

            chapter_id = f"ch_{i+1:04d}"
            chapters.append(Chapter(
                chapter_id=chapter_id,
                title=title,
                start=cluster[0].timestamp,
                end=cluster[-1].timestamp,
                event_count=len(cluster),
                dominant_type=dominant_type,
                key_people=key_people,
                key_places=key_places,
            ))

        return chapters

    def _generate_chapter_title(
        self,
        events: list[TimelineEvent],
        dominant_type: str,
        key_people: list[str],
        key_places: list[str],
    ) -> str:
        """Generate a human-readable chapter title.

        Uses heuristics — AI-generated titles come later via the swarm.
        """
        start = events[0].timestamp
        end = events[-1].timestamp
        duration = (end - start).days

        # Time description
        if duration <= 1:
            time_desc = start.strftime("%B %d, %Y")
        elif duration <= 7:
            time_desc = f"{start.strftime('%B %d')} - {end.strftime('%d, %Y')}"
        else:
            time_desc = start.strftime("%B %Y")

        # Content description
        if key_places:
            return f"{key_places[0]} — {time_desc}"
        elif key_people and len(key_people) <= 2:
            people_str = " & ".join(key_people)
            return f"With {people_str} — {time_desc}"
        elif dominant_type:
            type_labels = {
                "email": "Correspondence",
                "photo": "Photos",
                "media": "Media",
                "social": "Social Activity",
                "document": "Documents",
                "task": "Projects",
                "note": "Notes",
            }
            label = type_labels.get(dominant_type, dominant_type.title())
            return f"{label} — {time_desc}"
        else:
            return time_desc

    # ── Querying ────────────────────────────────────────────────────

    def query(
        self,
        start: Optional[datetime] = None,
        end: Optional[datetime] = None,
        source_type: Optional[str] = None,
        person: Optional[str] = None,
        place: Optional[str] = None,
        chapter_id: Optional[str] = None,
        zoom: ZoomLevel = ZoomLevel.MONTH,
        limit: int = 100,
    ) -> list[dict]:
        """Query timeline events with filters.

        Returns events grouped by the zoom level.
        """
        filtered = self._events

        if start:
            filtered = [e for e in filtered if e.timestamp >= start]
        if end:
            filtered = [e for e in filtered if e.timestamp <= end]
        if source_type:
            filtered = [e for e in filtered if e.source_type == source_type]
        if person:
            person_lower = person.lower()
            filtered = [e for e in filtered
                       if any(person_lower in p.lower() for p in e.people)]
        if place:
            place_lower = place.lower()
            filtered = [e for e in filtered
                       if any(place_lower in p.lower() for p in e.places)]
        if chapter_id:
            filtered = [e for e in filtered if e.chapter_id == chapter_id]

        # Apply limit
        filtered = filtered[:limit]

        # Group by zoom level
        if zoom == ZoomLevel.LIFE:
            return [e.to_dict() for e in filtered]

        groups: dict[str, list[dict]] = defaultdict(list)
        for event in filtered:
            key = self._zoom_key(event.timestamp, zoom)
            groups[key].append(event.to_dict())

        return [
            {"period": key, "events": events, "count": len(events)}
            for key, events in sorted(groups.items())
        ]

    def _zoom_key(self, dt: datetime, zoom: ZoomLevel) -> str:
        """Generate a grouping key for a timestamp at a given zoom level."""
        if zoom == ZoomLevel.DAY:
            return dt.strftime("%Y-%m-%d")
        elif zoom == ZoomLevel.WEEK:
            return dt.strftime("%Y-W%W")
        elif zoom == ZoomLevel.MONTH:
            return dt.strftime("%Y-%m")
        elif zoom == ZoomLevel.YEAR:
            return str(dt.year)
        elif zoom == ZoomLevel.DECADE:
            return f"{(dt.year // 10) * 10}s"
        return dt.isoformat()

    def get_chapter_objects(self) -> list[Chapter]:
        """Get all detected chapters as Chapter objects."""
        return list(self._chapters)

    def get_chapters(self) -> list[dict]:
        """Get all detected chapters."""
        return [c.to_dict() for c in self._chapters]

    def get_stats(self) -> dict:
        """Get timeline statistics."""
        if not self._events:
            return {
                "account": self.account_address,
                "total_events": 0,
                "chapters": 0,
            }

        type_counts = defaultdict(int)
        for e in self._events:
            type_counts[e.source_type or "unknown"] += 1

        return {
            "account": self.account_address,
            "total_events": len(self._events),
            "chapters": len(self._chapters),
            "earliest": self._events[0].timestamp.isoformat(),
            "latest": self._events[-1].timestamp.isoformat(),
            "span_days": (self._events[-1].timestamp - self._events[0].timestamp).days,
            "by_type": dict(type_counts),
            "unique_people": len(set(p for e in self._events for p in e.people)),
            "unique_places": len(set(p for e in self._events for p in e.places)),
        }
