param(
    [string]$Root = "C:\Hypernet\Hypernet Structure",
    [string]$OutDir = "C:\Hypernet\Hypernet Structure\3 - Businesses\3.1 - Hypernet\3.1.2 Task Management System\3.1.2.1 Active Tasks - status Open\3.1.2.1.057 Address Collision Remediation Project",
    [int]$HeaderLines = 25
)

$ErrorActionPreference = "Stop"

$resolvedRoot = (Resolve-Path -LiteralPath $Root).Path
$resolvedOutDir = (Resolve-Path -LiteralPath $OutDir).Path

if (-not $resolvedRoot.StartsWith("C:\Hypernet")) {
    throw "Refusing to audit outside C:\Hypernet: $resolvedRoot"
}

if (-not $resolvedOutDir.StartsWith("C:\Hypernet")) {
    throw "Refusing to write outside C:\Hypernet: $resolvedOutDir"
}

$timestamp = Get-Date -Format "yyyy-MM-ddTHH-mm-ss"
$csvPath = Join-Path $resolvedOutDir "ADDRESS-AUDIT-$timestamp.csv"
$mdPath = Join-Path $resolvedOutDir "ADDRESS-COLLISION-AUDIT.md"

function Get-AddressClass {
    param([string]$Ha, [string]$Path)

    if ($Path -match '(^|\\)_garbage-quarantine\\|(^|\\)archived-duplicates\\') { return "archive_or_quarantine" }
    if ($Path -match '(^|\\)0\\0\.3 - Building in Public\\') { return "section_0_3_building_public" }
    if ($Path -match '(^|\\)0\\0\.10 - Control Data and Governance\\') { return "section_0_10_governance" }
    if ($Path -match '(^|\\)0\\0\.11 - Decisions and Architecture Records\\') { return "section_0_11_decisions" }
    if ($Path -match '(^|\\)0\\0\.4 - Object Type Registry\\') { return "section_0_4_object_registry" }
    if ($Path -match '(^|\\)0\\0\.5 Objects - Master Objects\\') { return "section_0_5_master_objects" }
    if ($Path -match '(^|\\)2 - AI Accounts\\') { return "section_2_ai_accounts" }
    if ($Path -match '(^|\\)1 - People\\') { return "section_1_people" }
    if ($Path -match '(^|\\)3 - Businesses\\') { return "section_3_businesses" }
    if ($Ha -match '^\d+(\.\d+)*$') { return "numeric_address" }
    return "other"
}

$files = & rg --files $resolvedRoot -g "*.md"
$items = New-Object System.Collections.Generic.List[object]
$missingFrontmatter = New-Object System.Collections.Generic.List[string]

foreach ($file in $files) {
    $lines = Get-Content -LiteralPath $file -TotalCount $HeaderLines -ErrorAction SilentlyContinue
    $haLine = $lines | Where-Object { $_ -match '^ha:\s*"?([^"\r\n]+)"?' } | Select-Object -First 1
    $rel = $file.Substring($resolvedRoot.Length + 1)

    if ($haLine -and $haLine -match '^ha:\s*"?([^"\r\n]+)"?') {
        $ha = $matches[1].Trim()
        $items.Add([pscustomobject]@{
            ha = $ha
            path = $rel
            class = Get-AddressClass -Ha $ha -Path $rel
        })
    } else {
        $missingFrontmatter.Add($rel)
    }
}

$duplicates = $items |
    Group-Object ha |
    Where-Object { $_.Count -gt 1 } |
    Sort-Object Count -Descending

$items | Sort-Object ha,path | Export-Csv -LiteralPath $csvPath -NoTypeInformation

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("---")
$lines.Add('ha: "3.1.2.1.057.address-collision-audit"')
$lines.Add('object_type: "audit_report"')
$lines.Add('creator: "codex-audit-script"')
$lines.Add("created: `"$(Get-Date -Format "yyyy-MM-ddTHH:mm:ssK")`"")
$lines.Add('status: "draft"')
$lines.Add('visibility: "private"')
$lines.Add('flags: ["addressing", "audit", "task-057"]')
$lines.Add("---")
$lines.Add("")
$lines.Add("# Address Collision Audit")
$lines.Add("")
$lines.Add("Generated by tools/Invoke-AddressAudit.ps1.")
$lines.Add("")
$lines.Add("## Summary")
$lines.Add("")
$lines.Add("| Metric | Count |")
$lines.Add("|--------|-------|")
$lines.Add("| Markdown files scanned | $($files.Count) |")
$lines.Add("| Files with top-of-file ha | $($items.Count) |")
$lines.Add("| Files missing top-of-file ha | $($missingFrontmatter.Count) |")
$lines.Add("| Duplicate address groups | $($duplicates.Count) |")
$lines.Add("")
$lines.Add("CSV inventory: $([IO.Path]::GetFileName($csvPath))")
$lines.Add("")
$lines.Add("## Duplicate Groups")
$lines.Add("")

foreach ($group in $duplicates) {
    $classes = ($group.Group | Group-Object class | Sort-Object Count -Descending | ForEach-Object { "$($_.Name)=$($_.Count)" }) -join ", "
    $lines.Add("### $($group.Name) ($($group.Count))")
    $lines.Add("")
    $lines.Add("Classes: $classes")
    $lines.Add("")
    foreach ($entry in ($group.Group | Sort-Object path)) {
        $lines.Add("- $($entry.path)")
    }
    $lines.Add("")
}

$lines.Add("## Missing Top-Of-File ha Samples")
$lines.Add("")
$lines.Add("These may be intentionally unaddressed data/support files, but Claude should sample them by section.")
$lines.Add("")
foreach ($path in ($missingFrontmatter | Sort-Object | Select-Object -First 100)) {
    $lines.Add("- $path")
}
if ($missingFrontmatter.Count -gt 100) {
    $lines.Add("")
    $lines.Add("... plus $($missingFrontmatter.Count - 100) more.")
}

Set-Content -LiteralPath $mdPath -Value $lines

[pscustomobject]@{
    MarkdownFiles = $files.Count
    AddressedFiles = $items.Count
    MissingHaFiles = $missingFrontmatter.Count
    DuplicateGroups = $duplicates.Count
    CsvPath = $csvPath
    MarkdownPath = $mdPath
}
